# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.78859823 0.23415989 0.75335479]
  [0.25391445 0.02761992 0.93966842]
  [0.19210696 0.25791388 0.0138328 ]]

 [[0.89165786 0.80817979 0.77486173]
  [0.29616742 0.62455327 0.40552304]
  [0.10474409 0.23957933 0.51046184]]

 [[0.10648135 0.20054714 0.7800431 ]
  [0.18355834 0.79242899 0.18442697]
  [0.62423251 0.40116708 0.99126933]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a = np.diag(1 + np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)    

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [10]:
x= np.random.random((5,5))
print("Original Array:",)
print(x)

xmax, xmin = x.max(), x.min()

x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.2293491  0.23955076 0.35470088 0.51528341 0.71796465]
 [0.16745895 0.08625533 0.85259684 0.21909268 0.39310686]
 [0.27534462 0.52837722 0.15939609 0.97895234 0.98431767]
 [0.42576374 0.55554155 0.85655404 0.99587608 0.78987608]
 [0.86231511 0.3081532  0.20082194 0.30151395 0.67476726]]
After normalization:
[[0.15731146 0.16852675 0.2951181  0.471656   0.69447549]
 [0.08927195 0.         0.84248465 0.14603597 0.33734007]
 [0.20787706 0.4860508  0.08040797 0.98139474 0.98729315]
 [0.37324171 0.51591416 0.84683503 1.         0.773532  ]
 [0.85316851 0.24394548 0.12594987 0.23664656 0.64698605]]


# 5.  How to find common values between two arrays?

In [12]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [14]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yestraday: ",yesterday)
today     = np.datetime64('today')
print("Today: ",today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [21]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 0 1 0 0]
Second array:
[0 0 1 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [26]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.88340049 0.10634443 0.05916486 0.22763477 0.58539582 0.30023796
 0.81368606 0.40464892 0.56841226 0.27501684]
Maximum value replaced by 0:
[0.         0.10634443 0.05916486 0.22763477 0.58539582 0.30023796
 0.81368606 0.40464892 0.56841226 0.27501684]


# 9. How to print all the values of an array?

In [31]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((16,16))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [35]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.14359273 -0.23958266 -0.28947555  0.34078423  0.10948868 -0.42307279
   0.44629329  0.45130048 -0.43132767 -0.10800074]
 [-0.10484695  0.18599184 -0.05094935  0.0558446   0.28696354  0.16702253
  -0.35330432  0.00711552  0.27521126 -0.46904866]
 [-0.209039    0.20989564 -0.1669347   0.4374255   0.06186177 -0.21028577
  -0.0448002  -0.15780387  0.3930952  -0.31341457]
 [-0.32096661  0.12100187  0.38852235 -0.11974484  0.10749583 -0.18921005
  -0.53043421  0.33625001  0.3785542  -0.17146854]
 [ 0.11801898 -0.10104943 -0.02075827 -0.128946    0.0169444  -0.1026086
   0.34043637  0.11892023 -0.24534386  0.00438619]]
[[ 0.14359273 -0.23958266 -0.28947555  0.34078423  0.10948868 -0.42307279
   0.44629329  0.45130048 -0.43132767 -0.10800074]
 [-0.10484695  0.18599184 -0.05094935  0.0558446   0.28696354  0.16702253
  -0.35330432  0.00711552  0.27521126 -0.46904866]
 [-0.209039    0.20989564 -0.1669347   0.4374255   0.06186177 -0.21028577
  -0.0448002  -0.15780387  0.3930952  -0.31341457]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [6]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 4. 2. 2. 2. 1. 8. 2. 1.]


In [7]:
np.add.at(Z, I, 1)
print(Z)

[ 7.  7.  7.  3.  3.  3.  1. 15.  3.  1.]


# 12.How to get the diagonal of a dot product?

In [9]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.36088332 0.57417301 0.78054465 0.35430546 0.57063263]
 [0.19029783 0.38319132 0.88288534 0.10696611 0.15978569]
 [0.51069681 0.70968045 0.08820427 0.21762726 0.31454964]
 [0.41106504 0.29416459 0.19924305 0.70420705 0.84437906]
 [0.57318379 0.00246687 0.10040003 0.59840497 0.37459791]]
[[0.37465054 0.3273298  0.85835368 0.04163064 0.97848096]
 [0.25076904 0.52803167 0.04832199 0.82030219 0.29061483]
 [0.88036707 0.23222672 0.24844854 0.09794418 0.03457408]
 [0.17439553 0.15269317 0.67531236 0.14156808 0.40231332]
 [0.3504486  0.06335401 0.10580781 0.06895694 0.92158555]]
diagonal of a dot product method 1 is.... [1.22812245 0.49611293 0.67481407 0.43585049 1.15100788]
diagonal of a dot product method 2 is.... [1.22812245 0.49611293 0.67481407 0.43585049 1.15100788]


# 13.How to find the most frequent value in an array?

In [11]:
x = np.random.randint(0, 10, 30)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[4 5 9 0 7 1 5 8 6 4 9 9 4 6 8 6 2 5 1 9 8 7 9 5 5 3 5 7 7 8]
Most frequent value in the above array:
5


# 14.How to get the n largest values of an array

In [15]:
x = np.arange(100)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 2
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[98 99]


# 15.How to create a record array from a regular array?

In [18]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
